---
- name: set write permission on redmine folder
  file: path={{ redmine_home }}/{{ item }}
        state=directory
        owner={{ webserver_user }}
        group={{ redmine_user }}
        recurse=yes mode=0775
  with_items:
    - "files"
    - "log"
    - "tmp"
    - "public/plugin_assets"

- name: deploy apache site
  template: src=redmine.conf.j2 dest=/etc/apache2/sites-available/redmine.conf

- name: enable apache site
  file: src=/etc/apache2/sites-available/redmine.conf
        dest=/etc/apache2/sites-enabled/redmine.conf
        state=link
  notify:
    - restart apache

- name: ensure apache default website is disabled
  file: path=/etc/apache2/sites-enabled/000-default.conf
        state=absent
  notify:
    - restart apache

- name: change passenger user to apache
  lineinfile: dest=/etc/apache2/mods-enabled/passenger.conf
              line="PassengerUser {{ webserver_user }}"
              state=present
  notify:
    - restart apache
